autonomy:
  mode: high
  description: >
    Autonomous execution is permitted within predefined technical scope.
    The agent may operate without human initiation once configured.

triggers:
  scheduled:
    enabled: true
    cadence: nightly
  manual:
    enabled: true
  event_based:
    enabled: false

execution:
  task_selection: agent_selected
  max_tasks_per_run: 1
  task_scope: single_scoped_improvement

change_control:
  branch_creation: required
  direct_commits_to_main: false
  pull_request_required: true

auto_merge:
  enabled: true
  conditions:
    - all_tests_pass
    - no_ethics_violation
    - no_scope_violation
    - no_clawd_file_changes
    - audit_bundle_complete

safety_limits:
  max_files_changed: 25
  max_lines_changed: 800
  forbidden_paths:
    - clawd/
    - .github/workflows/
    - governance/
    - policy/
    - legal/

failure_handling:
  on_test_failure: halt
  on_validation_failure: halt
  on_ethics_violation: halt
  on_unknown_error: halt

self_modification:
  allowed: false

logging:
  level: verbose
  persist_logs: true

override:
  human_override_allowed: true
  override_method: repository_settings
